### ISSUE TITLE
Where can I see the solution of the problems in the pdf?

### ISSUE THREAD

**Issue by lidh15** [davidwhogg/mcmc#33]
The error was 'latex' cannot be found when I tried to make the folder, and I have no idea about the outputs of the python scripts. I wonder what I could see if I got the pdfs generated by the scripts? Where are the solutions?

**Comment by dfm** [comment]
I guess you'll just have to do the exercises!

**Comment by dfm** [comment]
Some of the figures are in the paper. To see the other ones, you'll need to figure out your Python environment (it's not my job to help you figure that out) or do the exercises yourself!

**Comment by lidh15** [comment]
Well, I find this seems to be part of a course of Mr Hogg. If it is so, I am sorry for bothering. I am just a visitor.
