### ISSUE TITLE
make sure we discuss "marginalization is trivial"

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/mcmc#9]
we need to explicitly say that the sampling for `p(a, b | d)` is just the sampling for `p(a, b, c, x | d)` with the `c` and `x` values ignored.  That's key!

**Comment by eggplantbren** [comment]
Feel free to steal https://github.com/eggplantbren/STATS331/blob/master/Figures/marginalisation.pdf
(source code for figure is https://github.com/eggplantbren/STATS331/blob/master/Figures/marginalisation.py)
